### ISSUE TITLE
CPU utilisation should be in the report

### ISSUE THREAD

**Issue by lkarsten** [varnish/varnishgather#10]
As Dag pointed out today, there should be some CPU core utilisation numbers in varnishgather. 

If varnish is doing excessive regex matches (lots of bans) or somehow has started using a lot of CPU, it isn't really obvious from the current data extracts.

mpstat -A was suggested for Linux. It comes from the sysstat package on rhel and debian, which doesn't seem to be installed by default.

**Comment by rezan** [comment]
mpstat and ps aux both provide this
