### ISSUE TITLE
Automatic upload function

### ISSUE THREAD

**Issue by lkarsten** [varnish/varnishgather#13]
We have a small file upload service for customers to send us huge files that isn't possible to send via email.

varnishgather could be extended to have a upload-to-url function, where the produced output file could be POST-ed via curl/wget to this URL.

Since this is HTTP we don't have the usual file size limitations that SMTP has.

This will make data collection simpler for the customer/user.

**Comment by freshteapot** [comment]
@espebra Do we do anything special with filebin? as it clearly expects some sort of generated bin id. I read the html and looked at the docs over https://github.com/espebra/filebin.

**Comment by espebra** [comment]
It is possible to specify the bin using the ``bin`` request header. If not specified, it will be randomly generated. The bin will be part of the url: https://filebin.varnish-software.com/$BIN/$FILENAME

**Comment by freshteapot** [comment]
```
curl -XPOST -i --data-binary @./hello.txt  https://filebin.varnish-software.com
HTTP/1.1 400 Bad Request
Content-Type: text/plain; charset=utf-8
X-Content-Type-Options: nosniff
Date: Wed, 26 Apr 2017 12:06:17 GMT
Content-Length: 12
X-Varnish: 101202
Age: 0
Via: 1.1 varnish-v4
Connection: keep-alive

Invalid bin
```

Then I am terrible at this http stuff :P

**Comment by espebra** [comment]
```
$ curl -i --data-binary @hello.txt -H "filename: hello.txt" -H "bin: somecustombin" https://filebin.varnish-software.com
HTTP/1.1 201 Created
Content-Type: application/json
Date: Wed, 26 Apr 2017 13:00:06 GMT
Content-Length: 560
X-Varnish: 230754
Age: 0
Via: 1.1 varnish-v4
Connection: keep-alive

{
    "filename": "hello.txt",
    "bin": "somecustombin",
    "bytes": 4,
    "mime": "application/octet-stream",
    "created": "2017-04-26T13:00:06.761193473Z",
    "checksum": "b5bb9d8014a0f9b1d61e21e796d78dccdf1352f23cd32812f4850b878ae4944c",
    "links": [
        {
            "rel": "file",
            "href": "https://filebin.varnish-software.com/somecustombin/hello.txt"
        },
        {
            "rel": "bin",
            "href": "https://filebin.varnish-software.com/somecustombin"
        }
    ],
    "datetime": "0001-01-01T00:00:00Z"
}
```

**Comment by freshteapot** [comment]
Okay :), so if we went forward with this. we would want to create a random id :)

Thank you for the example @espebra .

**Comment by stone** [comment]
Added option -u in #47 (based on curl and filebin.varnish-software.com)
