### ISSUE TITLE
Long running varnishlog

### ISSUE THREAD

**Issue by espebra** [varnish/varnishgather#24]
Varnishlog runs with ``-d -k 20000``, which runs with no problems on a busy system. On an idle system, however, it will hang for a long time while waiting for 20000 requests. Some timeout might be appropriate.

**Comment by perbu** [comment]
timeout(1) might be a good way to solve it in the gather.
$timeout -s TERM -k 15 10 varnishlog -d -k 20000

Will timeout (TERM) after 10 seconds and KILL it after 15 seconds if it is still running.

**Comment by Dridi** [comment]
With an external dependency we need to look for `timeout` on the target system and either complain about or ignore its absence.

I've suggested in the past that we package `varnishgather` along with the vcp package. That would make it available in the default path and enforce the presence of its dependencies to always ensure comprehensive reports.

**Comment by fgsch** [comment]
I mentioned this to Espen and have checked since we had the discussion.
timeout(1) is part of coreutils and present in EL6, EL7, Ubuntu and Debian.

I think we are safe.

**Comment by fgsch** [comment]
FWIW, -k is not available in older versions so I left it out.
