### ISSUE TITLE
VHA nodes.conf has a new location

### ISSUE THREAD

**Issue by rezan** [varnish/varnishgather#28]
nodes.conf is no longer in /etc/vha-agent/, its now in /etc/varnish.

https://github.com/varnish/varnishgather/blob/a4ebe1713fec12f7d3a14a1476c1e833b5dfa03c/varnishgather#L470

**Comment by franciscovg** [comment]
Then the documentation has to be updated as well https://cabinet.varnish-software.com/Documents/installation-guide_ha-latest.pdf

**Comment by gquintard** [comment]
Fixed by 2fe2a2b
