### ISSUE TITLE
Gather the stats output from the varnish-agent

### ISSUE THREAD

**Issue by freshteapot** [varnish/varnishgather#33]
Via the agent, we return a slightly different version of stats, that you get via "varnishstat".

```
localhost:6085/stats
```

Potential problems:
- Getting the correct port it is listening on.
- Getting the username and password for use in "-u".

Possible command, if we assume defaults.

```
curl -u$(cat /etc/varnish/agent_secret) localhost:6085/stats -o stats.json
```

**Comment by rezan** [comment]
Please re-open if this is still needed.
