### ISSUE TITLE
insecure mode for uploading gather

### ISSUE THREAD

**Issue by simook** [varnish/varnishgather#68]
If a customer's environment has outdated ca certs, they will be unable to upload a varnish gather to our filebin service. 
It would be nice if we could provide a simple solution for our customers using varnishgather. 

For example, adding the `-k` argument to the script would enable the corresponding insecure mode in curl. 
`sh ./varnishgather -k -u simukka`

**Comment by gquintard** [comment]
I'm going to vote that one down, if you have outdated certs, you should fix them, and you can still grab the file and send it manually

**Comment by simook** [comment]
I agree @gquintard. But in this case, we had a customer who did have outdated certs and was having troubles trying to give us a gather. The insecure mode would have been helpful for that situation. We can't always expect a customer to update their certs, and in this case the customer did not have the authorization to update certs and also didn't seem willing to ask their IT/DevOps to update the certs. 

The workaround for that case was for the customer to upload it themselves.
