### ISSUE TITLE
Include VCS related information.

### ISSUE THREAD

**Issue by simook** [varnish/varnishgather#70]
- /status output
- logs

**Comment by simook** [comment]
_My apologies for the lack of detail in the original submitted issue._ 

### Background
When helping customers with Varnish Custom Statistics (VCS), we often have to request additional information in addition to the varnishgather.

When the VCS server process is running it has an API `/status` endpoint that provides useful runtime counters such as the number of keys and number of dropped messages. These counters are very useful and would be helpful to include in the varnishgather. 

### Implementation considerations
- The VCS server HTTP port can be customized by the customer. 
- Some customers do enable authentication for the VCS server HTTP interface.
- The runtime counters reset when the the VCS server starts.

**Comment by Zoljargal-Zolo-Jargalsaikhan** [comment]
Hello Team,
I am having a shot at this issue.
Just informing the team someone is working on this
